In [20]:
import numpy as np

In [21]:
np.__version__

'2.0.1'

## Create & Read

### 1D Array

In [22]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [23]:
type(arr1)

numpy.ndarray

In [24]:
arr1.shape

(6,)

In [25]:
arr1.dtype

dtype('int64')

In [26]:
arr1.ndim

1

In [27]:
arr1.size

6

### 2D Array

In [28]:
arr2 = np.array([[1, 4, 5], [6, 7, 1]])
arr2

array([[1, 4, 5],
       [6, 7, 1]])

In [29]:
arr2.ndim

2

In [30]:
arr2.shape # (row, column)

(2, 3)

In [31]:
arr2.dtype

dtype('int64')

In [32]:
arr2.size

6

### 3D Array

In [33]:
arr3 = np.array([[[1, 3, 5,], [2, 4, 8]], [[1, 4, 5], [6, 7, 1]], [[9, 3, 6], [4, 6,6]]])
arr3

array([[[1, 3, 5],
        [2, 4, 8]],

       [[1, 4, 5],
        [6, 7, 1]],

       [[9, 3, 6],
        [4, 6, 6]]])

In [34]:
arr3.ndim

3

In [35]:
arr3.shape

(3, 2, 3)

## Create Random Array

In [36]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.21118984, 0.17649022, 0.52452942],
        [0.77405753, 0.22419593, 0.05046678]],

       [[0.08262854, 0.29885016, 0.05807263],
        [0.29095701, 0.18838381, 0.38139366]],

       [[0.1644512 , 0.01874999, 0.06644487],
        [0.96488941, 0.23357093, 0.37241436]]])

In [37]:
randomArr.dtype

dtype('float64')

In [38]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
zeroes.ndim

3

In [40]:
full = np.full((3,2,3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [41]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [42]:
arr3

array([[[1, 3, 5],
        [2, 4, 8]],

       [[1, 4, 5],
        [6, 7, 1]],

       [[9, 3, 6],
        [4, 6, 6]]])

In [43]:
arr3[0][0][2]

np.int64(5)

In [44]:
arr3[0:2]

array([[[1, 3, 5],
        [2, 4, 8]],

       [[1, 4, 5],
        [6, 7, 1]]])

In [45]:
arr3[-1]

array([[9, 3, 6],
       [4, 6, 6]])

In [46]:
arr3[1][0][1]

np.int64(4)

In [47]:
arr3[1, 0, 1]

np.int64(4)

### Update and Delete

In [48]:
import numpy as np
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [49]:
a1

array([[[1.96245950e-02, 1.39506634e-01],
        [9.90358438e-01, 1.40383003e-01],
        [3.86985839e-01, 2.75587923e-01]],

       [[5.36862022e-01, 2.64189060e-01],
        [3.98107082e-01, 6.23366524e-04],
        [2.55766707e-01, 5.03453778e-02]]])

In [50]:
a2

array([[[0.22209352, 0.40227548],
        [0.98839554, 0.16594702],
        [0.00633764, 0.97312966]],

       [[0.44122845, 0.63685112],
        [0.3971108 , 0.08831963],
        [0.49679171, 0.70313675]]])

### Basic Math Operations

In [51]:
np.add(a1, a2)

array([[[0.24171811, 0.54178212],
        [1.97875398, 0.30633002],
        [0.39332348, 1.24871758]],

       [[0.97809047, 0.90104018],
        [0.79521788, 0.088943  ],
        [0.75255842, 0.75348212]]])

In [52]:
np.subtract(a1, a2)

array([[[-0.20246892, -0.26276885],
        [ 0.0019629 , -0.02556402],
        [ 0.3806482 , -0.69754173]],

       [[ 0.09563357, -0.37266206],
        [ 0.00099629, -0.08769627],
        [-0.24102501, -0.65279137]]])

In [53]:
np.divide(a1, a2)

array([[[8.83618545e-02, 3.46793778e-01],
        [1.00198595e+00, 8.45950737e-01],
        [6.10614682e+01, 2.83197538e-01]],

       [[1.21674389e+00, 4.14836455e-01],
        [1.00250884e+00, 7.05807406e-03],
        [5.14836903e-01, 7.16011190e-02]]])

In [54]:
np.multiply(a1, a2)

array([[[4.35849532e-03, 5.61200987e-02],
        [9.78865862e-01, 2.32961409e-02],
        [2.45257843e-03, 2.68182780e-01]],

       [[2.36878798e-01, 1.68249098e-01],
        [1.58092621e-01, 5.50555037e-05],
        [1.27062780e-01, 3.53996851e-02]]])

### Statistical Operations

In [55]:
sqrt = np.sqrt(25)
abso = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.max(a1)
maxs = np.max(a2)

In [56]:
sqrt

np.float64(5.0)

In [57]:
abso

np.int64(2)

In [58]:
power

np.int64(256)

In [59]:
log

np.float64(3.2188758248682006)

In [60]:
mins

np.float64(0.9903584379839199)

In [61]:
maxs

np.float64(0.9883955386665471)

In [62]:
arr3

array([[[1, 3, 5],
        [2, 4, 8]],

       [[1, 4, 5],
        [6, 7, 1]],

       [[9, 3, 6],
        [4, 6, 6]]])

### Update

In [67]:
arr3

array([[[1, 3, 5],
        [2, 4, 8]],

       [[1, 4, 5],
        [6, 7, 1]],

       [[9, 3, 6],
        [4, 6, 6]]])

In [68]:
arr3

array([[[1, 3, 5],
        [2, 4, 8]],

       [[1, 4, 5],
        [6, 7, 1]],

       [[9, 3, 6],
        [4, 6, 6]]])

In [69]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   3, 500],
        [  2,   4,   8]],

       [[  1,   4,   5],
        [  6,   7,   1]],

       [[  9,   3,   6],
        [  4,   6,   6]]])

In [70]:
arr3.sort()
arr3

array([[[  1,   3, 500],
        [  2,   4,   8]],

       [[  1,   4,   5],
        [  1,   6,   7]],

       [[  3,   6,   9],
        [  4,   6,   6]]])

In [71]:
# Reshape
arr3.shape

(3, 2, 3)

In [73]:
arr3_reshape = arr3.reshape(2, 3, -1)
arr3_reshape

array([[[  1,   3, 500],
        [  2,   4,   8],
        [  1,   4,   5]],

       [[  1,   6,   7],
        [  3,   6,   9],
        [  4,   6,   6]]])

In [74]:
arr3_reshape.shape

(2, 3, 3)

### Appending & Inserting

In [75]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = column

appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [77]:
# Insert

In [78]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [90]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [91]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.06702725, 0.98777931, 0.55682118],
        [0.97357492, 0.81049127, 0.89924163]],

       [[0.67920166, 0.68106695, 0.4726295 ],
        [0.38288848, 0.95783965, 0.42728649]],

       [[0.82081992, 0.26319625, 0.593967  ],
        [0.9790322 , 0.85515796, 0.45798731]]])

In [92]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [93]:
np.save("new_array", arr5)

In [94]:
np.load("new_array.npy")

array([[[0.97357492, 0.81049127, 0.89924163]],

       [[0.38288848, 0.95783965, 0.42728649]],

       [[0.9790322 , 0.85515796, 0.45798731]]])